 // <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TripProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from TripProto.proto</summary>
  public static partial class TripProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for TripProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TripProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9UcmlwUHJvdG8ucHJvdG8SBXByb3RvIjAKClV0aWxpemF0b3ISEAoIdXNl",
            "cm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiQwoJRmlsdGVyRFRPEhgK",
            "EG9iaWVjdGl2VHVyaXN0aWMYASABKAkSDAoEZGVMYRgCIAEoCRIOCgZwYW5h",
            "TGEYAyABKAkiYAoMUmV6ZXJ2YXJlRFRPEhIKCm51bWVDbGllbnQYASABKAkS",
            "FQoNdGVsZWZvbkNsaWVudBgCIAEoCRITCgtudW1hckxvY3VyaRgDIAEoBRIQ",
            "Cgh1c2VybmFtZRgEIAEoBSKOAQoLRXhjdXJzaWVEVE8SCgoCaWQYASABKAUS",
            "GAoQb2JpZWN0aXZUdXJpc3RpYxgCIAEoCRIWCg5maXJtYVRyYW5zcG9ydBgD",
            "IAEoCRITCgtvcmFQbGVjYXJpaRgEIAEoCRIMCgRwcmV0GAUgASgBEh4KFm51",
            "bWFyTG9jdXJpRGlzcG9uaWJpbGUYBiABKAUisgIKB1JlcXVlc3QSKAoEdHlw",
            "ZRgBIAEoDjIaLnByb3RvLlJlcXVlc3QuUmVxdWVzdFR5cGUSJwoKdXRpbGl6",
            "YXRvchgCIAEoCzIRLnByb3RvLlV0aWxpemF0b3JIABISCgh1c2VybmFtZRgD",
            "IAEoCUgAEiIKBmZpbHRlchgEIAEoCzIQLnByb3RvLkZpbHRlckRUT0gAEigK",
            "CXJlemVydmFyZRgFIAEoCzITLnByb3RvLlJlemVydmFyZURUT0gAImoKC1Jl",
            "cXVlc3RUeXBlEgkKBUxPR0lOEAASCgoGTE9HT1VUEAESDAoIUkVHSVNURVIQ",
            "AhINCglHRVRfVFJJUFMQAxIWChJHRVRfVFJJUFNfRklMVEVSRUQQBBIPCgtS",
            "RVNFUlZBVElPThAFQgYKBGRhdGEi5gEKCFJlc3BvbnNlEikKBHR5cGUYASAB",
            "KA4yGy5wcm90by5SZXNwb25zZS5SZXBvbnNlVHlwZRINCgVlcnJvchgCIAEo",
            "CRIlCgp1dGlsaXphdG9yGAMgASgLMhEucHJvdG8uVXRpbGl6YXRvchIkCghl",
            "eGN1cnNpaRgEIAMoCzISLnByb3RvLkV4Y3Vyc2llRFRPIlMKC1JlcG9uc2VU",
            "eXBlEgYKAk9LEAASCQoFRVJST1IQARINCglHRVRfVFJJUFMQAhIWChJHRVRf",
            "VFJJUFNfRklMVEVSRUQQAxIKCgZVUERBVEUQBEItCh1vcmcuZXhhbXBsZS5w",
            "cm90b2J1ZmZwcm90b2NvbEIMVHJpcFByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Utilizator), global::Proto.Utilizator.Parser, new[]{ "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.FilterDTO), global::Proto.FilterDTO.Parser, new[]{ "ObiectivTuristic", "DeLa", "PanaLa" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.RezervareDTO), global::Proto.RezervareDTO.Parser, new[]{ "NumeClient", "TelefonClient", "NumarLocuri", "Username" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.ExcursieDTO), global::Proto.ExcursieDTO.Parser, new[]{ "Id", "ObiectivTuristic", "FirmaTransport", "OraPlecarii", "Pret", "NumarLocuriDisponibile" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Request), global::Proto.Request.Parser, new[]{ "Type", "Utilizator", "Username", "Filter", "Rezervare" }, new[]{ "Data" }, new[]{ typeof(global::Proto.Request.Types.RequestType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Response), global::Proto.Response.Parser, new[]{ "Type", "Error", "Utilizator", "Excursii" }, null, new[]{ typeof(global::Proto.Response.Types.ReponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Utilizator : pb::IMessage<Utilizator>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Utilizator> _parser = new pb::MessageParser<Utilizator>(() => new Utilizator());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Utilizator> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TripProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Utilizator() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Utilizator(Utilizator other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Utilizator Clone() {
      return new Utilizator(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Utilizator);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Utilizator other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Utilizator other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class FilterDTO : pb::IMessage<FilterDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<FilterDTO> _parser = new pb::MessageParser<FilterDTO>(() => new FilterDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<FilterDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TripProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterDTO(FilterDTO other) : this() {
      obiectivTuristic_ = other.obiectivTuristic_;
      deLa_ = other.deLa_;
      panaLa_ = other.panaLa_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterDTO Clone() {
      return new FilterDTO(this);
    }

    /// <summary>Field number for the "obiectivTuristic" field.</summary>
    public const int ObiectivTuristicFieldNumber = 1;
    private string obiectivTuristic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObiectivTuristic {
      get { return obiectivTuristic_; }
      set {
        obiectivTuristic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "deLa" field.</summary>
    public const int DeLaFieldNumber = 2;
    private string deLa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DeLa {
      get { return deLa_; }
      set {
        deLa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "panaLa" field.</summary>
    public const int PanaLaFieldNumber = 3;
    private string panaLa_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PanaLa {
      get { return panaLa_; }
      set {
        panaLa_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as FilterDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(FilterDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ObiectivTuristic != other.ObiectivTuristic) return false;
      if (DeLa != other.DeLa) return false;
      if (PanaLa != other.PanaLa) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ObiectivTuristic.Length != 0) hash ^= ObiectivTuristic.GetHashCode();
      if (DeLa.Length != 0) hash ^= DeLa.GetHashCode();
      if (PanaLa.Length != 0) hash ^= PanaLa.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObiectivTuristic);
      }
      if (DeLa.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeLa);
      }
      if (PanaLa.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PanaLa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ObiectivTuristic);
      }
      if (DeLa.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DeLa);
      }
      if (PanaLa.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PanaLa);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ObiectivTuristic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObiectivTuristic);
      }
      if (DeLa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DeLa);
      }
      if (PanaLa.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PanaLa);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(FilterDTO other) {
      if (other == null) {
        return;
      }
      if (other.ObiectivTuristic.Length != 0) {
        ObiectivTuristic = other.ObiectivTuristic;
      }
      if (other.DeLa.Length != 0) {
        DeLa = other.DeLa;
      }
      if (other.PanaLa.Length != 0) {
        PanaLa = other.PanaLa;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 18: {
            DeLa = input.ReadString();
            break;
          }
          case 26: {
            PanaLa = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 18: {
            DeLa = input.ReadString();
            break;
          }
          case 26: {
            PanaLa = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RezervareDTO : pb::IMessage<RezervareDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RezervareDTO> _parser = new pb::MessageParser<RezervareDTO>(() => new RezervareDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RezervareDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TripProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RezervareDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RezervareDTO(RezervareDTO other) : this() {
      numeClient_ = other.numeClient_;
      telefonClient_ = other.telefonClient_;
      numarLocuri_ = other.numarLocuri_;
      username_ = other.username_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RezervareDTO Clone() {
      return new RezervareDTO(this);
    }

    /// <summary>Field number for the "numeClient" field.</summary>
    public const int NumeClientFieldNumber = 1;
    private string numeClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NumeClient {
      get { return numeClient_; }
      set {
        numeClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "telefonClient" field.</summary>
    public const int TelefonClientFieldNumber = 2;
    private string telefonClient_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TelefonClient {
      get { return telefonClient_; }
      set {
        telefonClient_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "numarLocuri" field.</summary>
    public const int NumarLocuriFieldNumber = 3;
    private int numarLocuri_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumarLocuri {
      get { return numarLocuri_; }
      set {
        numarLocuri_ = value;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 4;
    private int username_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Username {
      get { return username_; }
      set {
        username_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RezervareDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RezervareDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NumeClient != other.NumeClient) return false;
      if (TelefonClient != other.TelefonClient) return false;
      if (NumarLocuri != other.NumarLocuri) return false;
      if (Username != other.Username) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NumeClient.Length != 0) hash ^= NumeClient.GetHashCode();
      if (TelefonClient.Length != 0) hash ^= TelefonClient.GetHashCode();
      if (NumarLocuri != 0) hash ^= NumarLocuri.GetHashCode();
      if (Username != 0) hash ^= Username.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NumeClient.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumeClient);
      }
      if (TelefonClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TelefonClient);
      }
      if (NumarLocuri != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumarLocuri);
      }
      if (Username != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Username);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NumeClient.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(NumeClient);
      }
      if (TelefonClient.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TelefonClient);
      }
      if (NumarLocuri != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NumarLocuri);
      }
      if (Username != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Username);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NumeClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NumeClient);
      }
      if (TelefonClient.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TelefonClient);
      }
      if (NumarLocuri != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumarLocuri);
      }
      if (Username != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Username);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RezervareDTO other) {
      if (other == null) {
        return;
      }
      if (other.NumeClient.Length != 0) {
        NumeClient = other.NumeClient;
      }
      if (other.TelefonClient.Length != 0) {
        TelefonClient = other.TelefonClient;
      }
      if (other.NumarLocuri != 0) {
        NumarLocuri = other.NumarLocuri;
      }
      if (other.Username != 0) {
        Username = other.Username;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            NumeClient = input.ReadString();
            break;
          }
          case 18: {
            TelefonClient = input.ReadString();
            break;
          }
          case 24: {
            NumarLocuri = input.ReadInt32();
            break;
          }
          case 32: {
            Username = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            NumeClient = input.ReadString();
            break;
          }
          case 18: {
            TelefonClient = input.ReadString();
            break;
          }
          case 24: {
            NumarLocuri = input.ReadInt32();
            break;
          }
          case 32: {
            Username = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExcursieDTO : pb::IMessage<ExcursieDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExcursieDTO> _parser = new pb::MessageParser<ExcursieDTO>(() => new ExcursieDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExcursieDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TripProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExcursieDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExcursieDTO(ExcursieDTO other) : this() {
      id_ = other.id_;
      obiectivTuristic_ = other.obiectivTuristic_;
      firmaTransport_ = other.firmaTransport_;
      oraPlecarii_ = other.oraPlecarii_;
      pret_ = other.pret_;
      numarLocuriDisponibile_ = other.numarLocuriDisponibile_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExcursieDTO Clone() {
      return new ExcursieDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "obiectivTuristic" field.</summary>
    public const int ObiectivTuristicFieldNumber = 2;
    private string obiectivTuristic_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ObiectivTuristic {
      get { return obiectivTuristic_; }
      set {
        obiectivTuristic_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "firmaTransport" field.</summary>
    public const int FirmaTransportFieldNumber = 3;
    private string firmaTransport_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirmaTransport {
      get { return firmaTransport_; }
      set {
        firmaTransport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oraPlecarii" field.</summary>
    public const int OraPlecariiFieldNumber = 4;
    private string oraPlecarii_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OraPlecarii {
      get { return oraPlecarii_; }
      set {
        oraPlecarii_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pret" field.</summary>
    public const int PretFieldNumber = 5;
    private double pret_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Pret {
      get { return pret_; }
      set {
        pret_ = value;
      }
    }

    /// <summary>Field number for the "numarLocuriDisponibile" field.</summary>
    public const int NumarLocuriDisponibileFieldNumber = 6;
    private int numarLocuriDisponibile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumarLocuriDisponibile {
      get { return numarLocuriDisponibile_; }
      set {
        numarLocuriDisponibile_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExcursieDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExcursieDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (ObiectivTuristic != other.ObiectivTuristic) return false;
      if (FirmaTransport != other.FirmaTransport) return false;
      if (OraPlecarii != other.OraPlecarii) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Pret, other.Pret)) return false;
      if (NumarLocuriDisponibile != other.NumarLocuriDisponibile) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (ObiectivTuristic.Length != 0) hash ^= ObiectivTuristic.GetHashCode();
      if (FirmaTransport.Length != 0) hash ^= FirmaTransport.GetHashCode();
      if (OraPlecarii.Length != 0) hash ^= OraPlecarii.GetHashCode();
      if (Pret != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Pret);
      if (NumarLocuriDisponibile != 0) hash ^= NumarLocuriDisponibile.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObiectivTuristic);
      }
      if (FirmaTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FirmaTransport);
      }
      if (OraPlecarii.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OraPlecarii);
      }
      if (Pret != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Pret);
      }
      if (NumarLocuriDisponibile != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NumarLocuriDisponibile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (ObiectivTuristic.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ObiectivTuristic);
      }
      if (FirmaTransport.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FirmaTransport);
      }
      if (OraPlecarii.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OraPlecarii);
      }
      if (Pret != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(Pret);
      }
      if (NumarLocuriDisponibile != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NumarLocuriDisponibile);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (ObiectivTuristic.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ObiectivTuristic);
      }
      if (FirmaTransport.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirmaTransport);
      }
      if (OraPlecarii.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OraPlecarii);
      }
      if (Pret != 0D) {
        size += 1 + 8;
      }
      if (NumarLocuriDisponibile != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumarLocuriDisponibile);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExcursieDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.ObiectivTuristic.Length != 0) {
        ObiectivTuristic = other.ObiectivTuristic;
      }
      if (other.FirmaTransport.Length != 0) {
        FirmaTransport = other.FirmaTransport;
      }
      if (other.OraPlecarii.Length != 0) {
        OraPlecarii = other.OraPlecarii;
      }
      if (other.Pret != 0D) {
        Pret = other.Pret;
      }
      if (other.NumarLocuriDisponibile != 0) {
        NumarLocuriDisponibile = other.NumarLocuriDisponibile;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 26: {
            FirmaTransport = input.ReadString();
            break;
          }
          case 34: {
            OraPlecarii = input.ReadString();
            break;
          }
          case 41: {
            Pret = input.ReadDouble();
            break;
          }
          case 48: {
            NumarLocuriDisponibile = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            ObiectivTuristic = input.ReadString();
            break;
          }
          case 26: {
            FirmaTransport = input.ReadString();
            break;
          }
          case 34: {
            OraPlecarii = input.ReadString();
            break;
          }
          case 41: {
            Pret = input.ReadDouble();
            break;
          }
          case 48: {
            NumarLocuriDisponibile = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TripProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.DataCase) {
        case DataOneofCase.Utilizator:
          Utilizator = other.Utilizator.Clone();
          break;
        case DataOneofCase.Username:
          Username = other.Username;
          break;
        case DataOneofCase.Filter:
          Filter = other.Filter.Clone();
          break;
        case DataOneofCase.Rezervare:
          Rezervare = other.Rezervare.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.Request.Types.RequestType type_ = global::Proto.Request.Types.RequestType.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Request.Types.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "utilizator" field.</summary>
    public const int UtilizatorFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Utilizator Utilizator {
      get { return dataCase_ == DataOneofCase.Utilizator ? (global::Proto.Utilizator) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Utilizator;
      }
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return HasUsername ? (string) data_ : ""; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        dataCase_ = DataOneofCase.Username;
      }
    }
    /// <summary>Gets whether the "username" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUsername {
      get { return dataCase_ == DataOneofCase.Username; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "username" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUsername() {
      if (HasUsername) {
        ClearData();
      }
    }

    /// <summary>Field number for the "filter" field.</summary>
    public const int FilterFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.FilterDTO Filter {
      get { return dataCase_ == DataOneofCase.Filter ? (global::Proto.FilterDTO) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Filter;
      }
    }

    /// <summary>Field number for the "rezervare" field.</summary>
    public const int RezervareFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.RezervareDTO Rezervare {
      get { return dataCase_ == DataOneofCase.Rezervare ? (global::Proto.RezervareDTO) data_ : null; }
      set {
        data_ = value;
        dataCase_ = value == null ? DataOneofCase.None : DataOneofCase.Rezervare;
      }
    }

    private object data_;
    /// <summary>Enum of possible cases for the "data" oneof.</summary>
    public enum DataOneofCase {
      None = 0,
      Utilizator = 2,
      Username = 3,
      Filter = 4,
      Rezervare = 5,
    }
    private DataOneofCase dataCase_ = DataOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DataOneofCase DataCase {
      get { return dataCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData() {
      dataCase_ = DataOneofCase.None;
      data_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Utilizator, other.Utilizator)) return false;
      if (Username != other.Username) return false;
      if (!object.Equals(Filter, other.Filter)) return false;
      if (!object.Equals(Rezervare, other.Rezervare)) return false;
      if (DataCase != other.DataCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.Request.Types.RequestType.Login) hash ^= Type.GetHashCode();
      if (dataCase_ == DataOneofCase.Utilizator) hash ^= Utilizator.GetHashCode();
      if (HasUsername) hash ^= Username.GetHashCode();
      if (dataCase_ == DataOneofCase.Filter) hash ^= Filter.GetHashCode();
      if (dataCase_ == DataOneofCase.Rezervare) hash ^= Rezervare.GetHashCode();
      hash ^= (int) dataCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Utilizator) {
        output.WriteRawTag(18);
        output.WriteMessage(Utilizator);
      }
      if (HasUsername) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (dataCase_ == DataOneofCase.Filter) {
        output.WriteRawTag(34);
        output.WriteMessage(Filter);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        output.WriteRawTag(42);
        output.WriteMessage(Rezervare);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (dataCase_ == DataOneofCase.Utilizator) {
        output.WriteRawTag(18);
        output.WriteMessage(Utilizator);
      }
      if (HasUsername) {
        output.WriteRawTag(26);
        output.WriteString(Username);
      }
      if (dataCase_ == DataOneofCase.Filter) {
        output.WriteRawTag(34);
        output.WriteMessage(Filter);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        output.WriteRawTag(42);
        output.WriteMessage(Rezervare);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.Request.Types.RequestType.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (dataCase_ == DataOneofCase.Utilizator) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Utilizator);
      }
      if (HasUsername) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (dataCase_ == DataOneofCase.Filter) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Filter);
      }
      if (dataCase_ == DataOneofCase.Rezervare) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rezervare);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.Request.Types.RequestType.Login) {
        Type = other.Type;
      }
      switch (other.DataCase) {
        case DataOneofCase.Utilizator:
          if (Utilizator == null) {
            Utilizator = new global::Proto.Utilizator();
          }
          Utilizator.MergeFrom(other.Utilizator);
          break;
        case DataOneofCase.Username:
          Username = other.Username;
          break;
        case DataOneofCase.Filter:
          if (Filter == null) {
            Filter = new global::Proto.FilterDTO();
          }
          Filter.MergeFrom(other.Filter);
          break;
        case DataOneofCase.Rezervare:
          if (Rezervare == null) {
            Rezervare = new global::Proto.RezervareDTO();
          }
          Rezervare.MergeFrom(other.Rezervare);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Utilizator subBuilder = new global::Proto.Utilizator();
            if (dataCase_ == DataOneofCase.Utilizator) {
              subBuilder.MergeFrom(Utilizator);
            }
            input.ReadMessage(subBuilder);
            Utilizator = subBuilder;
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            global::Proto.FilterDTO subBuilder = new global::Proto.FilterDTO();
            if (dataCase_ == DataOneofCase.Filter) {
              subBuilder.MergeFrom(Filter);
            }
            input.ReadMessage(subBuilder);
            Filter = subBuilder;
            break;
          }
          case 42: {
            global::Proto.RezervareDTO subBuilder = new global::Proto.RezervareDTO();
            if (dataCase_ == DataOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            global::Proto.Utilizator subBuilder = new global::Proto.Utilizator();
            if (dataCase_ == DataOneofCase.Utilizator) {
              subBuilder.MergeFrom(Utilizator);
            }
            input.ReadMessage(subBuilder);
            Utilizator = subBuilder;
            break;
          }
          case 26: {
            Username = input.ReadString();
            break;
          }
          case 34: {
            global::Proto.FilterDTO subBuilder = new global::Proto.FilterDTO();
            if (dataCase_ == DataOneofCase.Filter) {
              subBuilder.MergeFrom(Filter);
            }
            input.ReadMessage(subBuilder);
            Filter = subBuilder;
            break;
          }
          case 42: {
            global::Proto.RezervareDTO subBuilder = new global::Proto.RezervareDTO();
            if (dataCase_ == DataOneofCase.Rezervare) {
              subBuilder.MergeFrom(Rezervare);
            }
            input.ReadMessage(subBuilder);
            Rezervare = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("LOGOUT")] Logout = 1,
        [pbr::OriginalName("REGISTER")] Register = 2,
        [pbr::OriginalName("GET_TRIPS")] GetTrips = 3,
        [pbr::OriginalName("GET_TRIPS_FILTERED")] GetTripsFiltered = 4,
        [pbr::OriginalName("RESERVATION")] Reservation = 5,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.TripProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      utilizator_ = other.utilizator_ != null ? other.utilizator_.Clone() : null;
      excursii_ = other.excursii_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.Response.Types.ReponseType type_ = global::Proto.Response.Types.ReponseType.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Response.Types.ReponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "utilizator" field.</summary>
    public const int UtilizatorFieldNumber = 3;
    private global::Proto.Utilizator utilizator_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.Utilizator Utilizator {
      get { return utilizator_; }
      set {
        utilizator_ = value;
      }
    }

    /// <summary>Field number for the "excursii" field.</summary>
    public const int ExcursiiFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Proto.ExcursieDTO> _repeated_excursii_codec
        = pb::FieldCodec.ForMessage(34, global::Proto.ExcursieDTO.Parser);
    private readonly pbc::RepeatedField<global::Proto.ExcursieDTO> excursii_ = new pbc::RepeatedField<global::Proto.ExcursieDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.ExcursieDTO> Excursii {
      get { return excursii_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Utilizator, other.Utilizator)) return false;
      if(!excursii_.Equals(other.excursii_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Proto.Response.Types.ReponseType.Ok) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (utilizator_ != null) hash ^= Utilizator.GetHashCode();
      hash ^= excursii_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Proto.Response.Types.ReponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (utilizator_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Utilizator);
      }
      excursii_.WriteTo(output, _repeated_excursii_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Proto.Response.Types.ReponseType.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (utilizator_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Utilizator);
      }
      excursii_.WriteTo(ref output, _repeated_excursii_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Proto.Response.Types.ReponseType.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (utilizator_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Utilizator);
      }
      size += excursii_.CalculateSize(_repeated_excursii_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Proto.Response.Types.ReponseType.Ok) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.utilizator_ != null) {
        if (utilizator_ == null) {
          Utilizator = new global::Proto.Utilizator();
        }
        Utilizator.MergeFrom(other.Utilizator);
      }
      excursii_.Add(other.excursii_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Proto.Response.Types.ReponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (utilizator_ == null) {
              Utilizator = new global::Proto.Utilizator();
            }
            input.ReadMessage(Utilizator);
            break;
          }
          case 34: {
            excursii_.AddEntriesFrom(input, _repeated_excursii_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Proto.Response.Types.ReponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (utilizator_ == null) {
              Utilizator = new global::Proto.Utilizator();
            }
            input.ReadMessage(Utilizator);
            break;
          }
          case 34: {
            excursii_.AddEntriesFrom(ref input, _repeated_excursii_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ReponseType {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("GET_TRIPS")] GetTrips = 2,
        [pbr::OriginalName("GET_TRIPS_FILTERED")] GetTripsFiltered = 3,
        [pbr::OriginalName("UPDATE")] Update = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
